#ifndef TYPES_H
#define TYPES_H
enum Type {TYPE_NOT_DEFINED = 37, TYPE_QSTRING, TYPE_STATION, TYPE_SECTION, TYPE_PVR, TYPE_REQUEST, TYPE_STREAM};
enum Commands {PLAN_BUZ = 0, PLAN_SUZ, CHANGE_TO, CACHE_OUT, LOAD_REQUEST_DIKON, LOAD_REQUEST_ZHENYA};
#endif // TYPES_H
